version: '3'
services:
  db_dev:
    image: postgres
    container_name: postgres_dev
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=customerdb_dev
    ports:
      - 5432:5432
    volumes:
      - pg-data-dev:/var/lib/postgresql/data

  db_test:
    image: postgres
    container_name: postgres_test
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=customerdb_test
    ports:
      - 5431:5432

volumes:
  pg-data-dev:
